[project]
name = "cad-base"
version = "0.1.0"
description = "Base CAD development package"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipdb",
    'ipython',
    'build123d>=0.10.0',
    "cadquery-ocp-novtk>=7.9.3.1",
    "yacv-server==0.12.1",
    'yacv-server',
    'typer',
]

[tool.setuptools]
py-modules = []
